language: java
jdk:
  - openjdk8

branches:
  only:
    - dev

notifications:
  slack: professor-lol:pAWHye0uRCUwO9GWDtqoKd5q

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - cd professorlol-web/src/front
  - npm install
  - cd ../../..

script: "./gradlew clean build"

