riot:
  token:
    key: X-Riot-Token
    value: RGAPI-1193a7ca-491b-473f-a287-7beeff15e67f
  uri:
    host: https://kr.api.riotgames.com
    league-entry-by-summoner: /lol/league/v4/entries/by-summoner/{encryptedSummonerId}
    summoner-by-name: /lol/summoner/v4/summoners/by-name/{summonerName}
    match-list-by-account: /lol/match/v4/matchlists/by-account/{encryptedAccountId}